const dramas=[{"name":"请陛下翻牌子","cover":"assets/dramas/4/cover.png","episodes":[{"src":"assets/dramas/4/episode-1.mp4.web.mp4","title":"第一集"},{"src":"assets/dramas/4/episode-2.mp4.web.mp4","title":"第二集"},{"src":"assets/dramas/4/episode-3.mp4.web.mp4","title":"第三集"}]},{"name":"秦始皇张飞都来我的养老院","cover":"assets/dramas/3/cover.png","episodes":[{"src":"assets/dramas/3/episode-1.mp4.web.mp4","title":"第一集"},{"src":"assets/dramas/3/episode-2.mp4.web.mp4","title":"第二集"},{"src":"assets/dramas/3/episode-3.mp4.web.mp4","title":"第三集"}]},{"name":"山海酒馆","cover":"assets/dramas/5/cover.png","episodes":[{"src":"assets/dramas/5/episode-1.mp4.web.mp4","title":"第一集"},{"src":"assets/dramas/5/episode-2.mp4.web.mp4","title":"第二集"},{"src":"assets/dramas/5/episode-3.mp4.web.mp4","title":"第三集"}]},{"name":"历史十大遗憾","cover":"assets/dramas/1/cover.png","episodes":[{"src":"assets/dramas/1/episode-1.mp4","title":"第一集"},{"src":"assets/dramas/1/episode-2.mp4","title":"第二集"},{"src":"assets/dramas/1/episode-3.mp4","title":"第三集"}]},{"name":"历史十大遗憾第二季","cover":"assets/dramas/2/cover.png","episodes":[{"src":"assets/dramas/2/episode-1.mp4.web.mp4","title":"第一集"},{"src":"assets/dramas/2/episode-2.mp4.web.mp4","title":"第二集"},{"src":"assets/dramas/2/episode-3.mp4.web.mp4","title":"第三集"}]}];
// IP系列内容独立配置，可替换名称、封面和各集视频。
const ipSeries=[{"name":"虚拟偶像之死","cover":"assets/ip-series/virtual-idol/cover.png","episodes":[{"src":"assets/ip-series/virtual-idol/episode-1.mp4","title":"第一集"},{"src":"assets/ip-series/virtual-idol/episode-2.mp4","title":"第二集"},{"src":"assets/ip-series/virtual-idol/episode-3.mp4","title":"第三集"}]},{"name":"末日方舟2：极限归途","cover":"assets/ip-series/ark-2/cover.png","episodes":[{"src":"assets/ip-series/ark-2/episode-1.mp4","title":"末日方舟2：极限归途"}]},{"name":"历史十大遗憾","cover":"assets/dramas/1/cover.png","episodes":[{"src":"assets/dramas/1/episode-1.mp4","title":"第一集"},{"src":"assets/dramas/1/episode-2.mp4","title":"第二集"},{"src":"assets/dramas/1/episode-3.mp4","title":"第三集"}]},{"name":"历史十大遗憾第二季","cover":"assets/dramas/2/cover.png","episodes":[{"src":"assets/dramas/2/episode-1.mp4.web.mp4","title":"第一集"},{"src":"assets/dramas/2/episode-2.mp4.web.mp4","title":"第二集"},{"src":"assets/dramas/2/episode-3.mp4.web.mp4","title":"第三集"}]},{"name":"历史十大遗憾第三季","cover":"assets/ip-series/ancients-3/season-3-cover.png","episodes":[{"src":"assets/ip-series/ancients-3/episode-1.mp4","title":"第一集"},{"src":"assets/ip-series/ancients-3/episode-2.mp4","title":"第二集"},{"src":"assets/ip-series/ancients-3/episode-3.mp4","title":"第三集"}]}];
const dramaDialog=document.querySelector('#drama-dialog');
const dramaEpisodes=dramaDialog.querySelector('.drama-episodes');
document.querySelectorAll('[data-drama], [data-series]').forEach(button=>button.addEventListener('click',()=>{
 const drama=button.hasAttribute('data-series')?ipSeries[Number(button.dataset.series)]:dramas[Number(button.dataset.drama)];dramaDialog.querySelector('.eyebrow').textContent=button.hasAttribute('data-series')?'IP SERIES':'HIT SERIES';document.querySelector('#drama-title').textContent=drama.name;
 dramaEpisodes.replaceChildren();
 dramaDialog.classList.toggle('single-episode',drama.episodes.length===1);
 drama.episodes.forEach(episode=>{const article=document.createElement('article');const title=document.createElement('h3');title.textContent=episode.title;const video=document.createElement('video');video.src=episode.src;video.controls=true;video.playsInline=true;video.preload='none';video.setAttribute('aria-label',drama.name+' '+episode.title);const error=document.createElement('p');error.hidden=true;error.textContent='视频暂时无法播放，请刷新后重试。';video.addEventListener('error',()=>{error.hidden=false});video.addEventListener('play',()=>document.querySelectorAll('video').forEach(other=>{if(other!==video)other.pause()}));article.append(title,video,error);dramaEpisodes.append(article)});
 document.querySelectorAll('video').forEach(video=>video.pause());dramaDialog.showModal();
 if(drama.episodes.length===1)dramaEpisodes.querySelector('video').play().catch(()=>{/* Playback controls are available if autoplay is blocked. */});
}));
dramaDialog.addEventListener('close',()=>{dramaEpisodes.querySelectorAll('video').forEach(video=>{video.pause();video.removeAttribute('src');video.load()});dramaEpisodes.replaceChildren()});
const dramaRow=document.querySelector('.drama-row');
function moveDrama(direction){dramaRow.scrollBy({left:direction*(dramaRow.querySelector('.drama-card').getBoundingClientRect().width+24),behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}
document.querySelector('#dramas-prev').addEventListener('click',()=>moveDrama(-1));document.querySelector('#dramas-next').addEventListener('click',()=>moveDrama(1));
dramaRow.addEventListener('keydown',event=>{if(event.target!==dramaRow)return;if(event.key==='ArrowLeft'||event.key==='ArrowRight'){event.preventDefault();moveDrama(event.key==='ArrowLeft'?-1:1)}});

const seriesRow=document.querySelector('#ip-series .drama-row');
function moveSeries(direction){seriesRow.scrollBy({left:direction*(seriesRow.querySelector('.drama-card').getBoundingClientRect().width+24),behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}
document.querySelector('#series-prev').addEventListener('click',()=>moveSeries(-1));document.querySelector('#series-next').addEventListener('click',()=>moveSeries(1));
seriesRow.addEventListener('keydown',event=>{if(event.target!==seriesRow)return;if(event.key==='ArrowLeft'||event.key==='ArrowRight'){event.preventDefault();moveSeries(event.key==='ArrowLeft'?-1:1)}});
